#import "../shared/_at.typ": *

#show: ad.with(
  title: "Worksheet 23",
  author: [Parth Bhargava · A0310667E],
  experiment: "",
  course: [*PC3261* \
  Classical Mechanics II],
  title-page: false,
  decorative: true
)

#set math.equation(numbering: none)
#set math.cases(gap: 1em)

#pbm("9.7")[
  Evaluate ${vb(r), vb(n) dot vb(L)}_(vb(q), vb(p))$ where $vb(r) = x vu(e)_x + y vu(e)_y + z vu(e)_z$ and $vb(n) = n_x vu(e)_x + n_y vu(e)_y + n_z vu(e)_z$ is a constant vector.

  *Angular momentum:* $vb(L) = vb(r) times vb(p)$, with components $L_k = sum_(i,j) epsilon_(i j k) x_i p_j$
]

#solution[
  *Express the Poisson bracket:*

  We want to calculate:
  $ {x_i, vb(n) dot vb(L)}_(vb(q), vb(p)) $

  for each component $x_i$ of $vb(r)$.

  *Expand $vb(n) dot vb(L)$:*

  $ vb(n) dot vb(L) = sum_j n_j L_j = sum_j n_j sum_(r, s) epsilon_(j r s) x_r p_s $

  *Calculate Poisson bracket:*

  $ {x_i, vb(n) dot vb(L)}_(vb(q), vb(p)) = {x_i, sum_j sum_(r, s) epsilon_(j r s) n_j x_r p_s}_(vb(q), vb(p)) $

  $ = sum_j sum_(r, s) epsilon_(j r s) n_j {x_i, x_r p_s}_(vb(q), vb(p)) $

  *Use Leibniz rule:*

  $ {x_i, x_r p_s}_(vb(q), vb(p)) = x_r {x_i, p_s}_(vb(q), vb(p)) + {x_i, x_r}_(vb(q), vb(p)) p_s $

  *Apply fundamental Poisson brackets:*

  $ cases(
    {x_i, p_s}_(vb(q), vb(p)) &= delta_(i s),
    {x_i, x_r}_(vb(q), vb(p)) &= 0
  ) $

  Therefore:
  $ {x_i, x_r p_s}_(vb(q), vb(p)) = x_r delta_(i s) $

  *Substitute back:*

  $ {x_i, vb(n) dot vb(L)}_(vb(q), vb(p)) &= sum_j sum_(r, s) epsilon_(j r s) n_j x_r delta_(i s) \
  &= sum_j sum_r epsilon_(j r i) n_j x_r $

  *Recognize as cross product:*

  The sum $sum_(j, r) epsilon_(j r i) n_j x_r$ is the $i$-th component of $vb(n) times vb(r)$.

  To see this, recall that the $i$-th component of $vb(n) times vb(r)$ is:
  $ (vb(n) times vb(r))_i = sum_(j, r) epsilon_(i j r) n_j x_r $

  We have $sum_(j, r) epsilon_(j r i) n_j x_r$. Using the property $epsilon_(j r i) = epsilon_(i j r)$ (cyclic permutation):
  $ sum_(j, r) epsilon_(j r i) n_j x_r = sum_(j, r) epsilon_(i j r) n_j x_r = (vb(n) times vb(r))_i $

  *Final answer:*

  #boxed[$ {vb(r), vb(n) dot vb(L)}_(vb(q), vb(p)) = vb(n) times vb(r) $]

  *Physical interpretation:*

  This result shows that the angular momentum $vb(L)$ generates infinitesimal rotations in phase space. Specifically, the Poisson bracket with $vb(n) dot vb(L)$ gives the infinitesimal rotation of the position vector about the axis $vb(n)$.

  More formally, if we consider the canonical transformation generated by $vb(n) dot vb(L)$:
  $ delta vb(r) = epsilon {vb(r), vb(n) dot vb(L)}_(vb(q), vb(p)) = epsilon (vb(n) times vb(r)) $

  This is precisely an infinitesimal rotation by angle $epsilon$ about the axis $vb(n)$, confirming that angular momentum is the generator of rotations in classical mechanics.
]

#pagebreak()

#pbm("9.8")[
  A projectile with mass $m$ is moving on the vertical $x y$-plane in a uniform gravitational field.

  *Hamiltonian:*
  $ H(x, y, p_x, p_y, t) = (p_x^2 + p_y^2)/(2m) + m g y $

  *Given functions:*
  $ cases(
    F_1 &equiv y - (p_y t)/m - 1/2 g t^2,
    F_2 &equiv x - (p_x t)/m
  ) $

  Show that $F_1$ and $F_2$ are constants of motion and find three other constants of motion.
]

#solution[
  *Hamilton's equations:*

  From the Hamiltonian, we have:
  $ cases(
    dot(x) &= pdv(H, p_x) = display(p_x/m)\, quad &dot(p)_x &= -pdv(H, x) = 0,
    dot(y) &= pdv(H, p_y) = display(p_y/m)\, quad &dot(p)_y &= -pdv(H, y) = -m g
  ) $

  *Check if $F_1$ is a constant of motion:*

  A function $F({q_i, p_i}, t)$ is a constant of motion if:
  $ (dif F)/(dif t) = {F, H}_(vb(q), vb(p)) + pdv(F, t) = 0 $

  For $F_1 = y - (p_y t)/m - (g t^2)/2$:

  Calculate the partial derivative:
  $ pdv(F_1, t) = -(p_y)/m - g t $

  Calculate the Poisson bracket:
  $ {F_1, H}_(vb(q), vb(p)) &= pdv(F_1, x) pdv(H, p_x) - pdv(F_1, p_x) pdv(H, x) + pdv(F_1, y) pdv(H, p_y) - pdv(F_1, p_y) pdv(H, y) \
  &= 0 dot p_x/m - 0 dot 0 + 1 dot p_y/m - (-t/m) dot (-m g) \
  &= p_y/m - (t dot m g)/m \
  &= p_y/m - g t $

  Therefore:
  $ (dif F_1)/(dif t) = {F_1, H}_(vb(q), vb(p)) + pdv(F_1, t) = (p_y/m - g t) + (-(p_y)/m - g t) = 0 $

  #boxed[$F_1$ is a constant of motion.]

  *Check if $F_2$ is a constant of motion:*

  For $F_2 = x - (p_x t)/m$:

  $ pdv(F_2, t) = -(p_x)/m $

  $ {F_2, H}_(vb(q), vb(p)) &= pdv(F_2, x) pdv(H, p_x) - pdv(F_2, p_x) pdv(H, x) + pdv(F_2, y) pdv(H, p_y) - pdv(F_2, p_y) pdv(H, y) \
  &= 1 dot p_x/m - (-t/m) dot 0 + 0 dot p_y/m - 0 dot (-m g) \
  &= p_x/m $

  Therefore:
  $ (dif F_2)/(dif t) = {F_2, H}_(vb(q), vb(p)) + pdv(F_2, t) = p_x/m - p_x/m = 0 $

  #boxed[$F_2$ is a constant of motion.]

  *Find three other constants of motion:*

  **Constant 1: The Hamiltonian itself**

  $ F_3 equiv H = (p_x^2 + p_y^2)/(2m) + m g y $

  Check:
  $ pdv(H, t) = 0 quad ("no explicit time dependence") $

  $ {H, H}_(vb(q), vb(p)) = 0 quad ("Poisson bracket of any function with itself vanishes") $

  Therefore:
  $ (dif H)/(dif t) = {H, H}_(vb(q), vb(p)) + pdv(H, t) = 0 + 0 = 0 $

  #boxed[$F_3 = H$ (total energy) is a constant of motion.]

  **Constant 2: Horizontal momentum**

  $ F_4 equiv p_x $

  From Hamilton's equations, we already know:
  $ dot(p)_x = -pdv(H, x) = 0 $

  #boxed[$F_4 = p_x$ (horizontal momentum) is a constant of motion.]

  **Constant 3: Modified vertical momentum**

  $ F_5 equiv p_y + m g t $

  The total time derivative is:
  $ dv(F_5, t) = {F_5, H}_(vb(q), vb(p)) + pdv(F_5, t) $

  Calculate the partial derivative with respect to time:
  $ pdv(F_5, t) = m g $

  Calculate the Poisson bracket:
  $ {F_5, H}_(vb(q), vb(p)) &= pdv(F_5, x) pdv(H, p_x) - pdv(F_5, p_x) pdv(H, x) + pdv(F_5, y) pdv(H, p_y) - pdv(F_5, p_y) pdv(H, y) \
  &= 0 dot p_x/m - 0 dot 0 + 0 dot p_y/m - 1 dot (m g) \
  &= -m g $

  Therefore:
  $ dv(F_5, t) = {F_5, H}_(vb(q), vb(p)) + pdv(F_5, t) = -m g + m g = 0 $

  #boxed[$F_5 = p_y + m g t$ is a constant of motion.]

  *Summary of five constants of motion:*
  #boxed[
  $ cases(
    F_1 &= y - display((p_y t)/m) - display((g t^2)/2) quad &("vertical position" - "free fall"),
    F_2 &= x - display((p_x t)/m) quad &("horizontal position" - "uniform motion"),
    F_3 &= H = display((p_x^2 + p_y^2)/(2m)) + m g y quad &("total energy"),
    F_4 &= p_x quad &("horizontal momentum"),
    F_5 &= p_y + m g t quad &("modified vertical momentum")
  ) $
  ]

  *Physical interpretation:* These constants encode the initial conditions and conserved quantities of projectile motion. $F_1$ and $F_2$ relate to the initial position, $F_4$ and $F_5$ to the initial momentum, and $F_3$ to the total energy.
]
