#import "../shared/_at.typ": *

#show: ad.with(
  title: "Worksheet 24",
  author: [Parth Bhargava · A0310667E],
  experiment: "",
  course: [*PC3261* \
  Classical Mechanics II],
  title-page: false,
  decorative: true
)

#set math.equation(numbering: none)
#set math.cases(gap: 1em)

#pbm("9.9")[
  Obtain the canonical transformation generated by $Lambda_1 (q, Q, t) = q Q$ and the Kamiltonian equations of motion.

  *Harmonic oscillator Hamiltonian:*
  $ H(q, p) = 1/2 m omega^2 q^2 + p^2/(2m) $
]

#solution[
  *Type 1 generating function:*

  Given $Lambda_1 (q, Q, t) = q Q$.

  For a Type 1 generating function $F_1(q, Q, t)$, the canonical transformation is obtained from:
  $ p = pdv(F_1, q) quad "and" quad P = -pdv(F_1, Q) $

  *Derive transformation equations:*

  $ Lambda_1 (q, Q, t) = q Q $

  $ p = pdv(Lambda_1, q) = Q $

  $ P = -pdv(Lambda_1, Q) = -q $

  To find the inverse transformation $(q, p) -> (Q, P)$, we solve:
  $ Q = p $ and $ P = -q $, which gives:
  $ Q(q, p) = p $ and $ P(q, p) = -q $

  However, the standard convention is to express $(Q, P)$ in terms of $(q, p)$. Using the phase space Lagrangian gauge transformation:
  $ P dot(Q) - K = p dot(q) - H + (dif Lambda_1)/(dif t) $

  where:
  $ (dif Lambda_1)/(dif t) = pdv(Lambda_1, q) dot(q) + pdv(Lambda_1, Q) dot(Q) + pdv(Lambda_1, t) = Q dot(q) + q dot(Q) $

  Substituting:
  $ P dot(Q) - K = p dot(q) - H + Q dot(q) + q dot(Q) $

  Rearranging:
  $ P dot(Q) - K = (p + Q) dot(q) + q dot(Q) - H $

  For this to hold for all $dot(q)$ and $dot(Q)$, we must have:
  $ cases(
    p + Q &= 0 quad => quad Q = -p,
    P - q &= 0 quad => quad P = q
  ) $

  Therefore:
  #boxed[$ cases(
    Q(q, p, t) &= -p,
    P(q, p, t) &= q
  ) $]

  *Kamiltonian:*

  $ K(Q, P, t) = H(q(Q, P), p(Q, P), t) - pdv(Lambda_1, t) $

  Since $pdv(Lambda_1, t) = 0$, $q = P$, and $p = -Q$:

  $ K(Q, P, t) = 1/2 m omega^2 P^2 + Q^2/(2m) $

  #boxed[$ K(Q, P, t) = 1/2 m omega^2 P^2 + Q^2/(2m) $]

  *Hamilton's equations in new coordinates:*

  $ cases(
    dot(Q) &= pdv(K, P) = m omega^2 P,
    dot(P) &= -pdv(K, Q) = -Q/m
  ) $

  Taking time derivatives:
  $ dot.double(Q) = m omega^2 dot(P) = m omega^2 (-Q/m) = -omega^2 Q $

  $ dot.double(P) = -dot(Q)/m = -(m omega^2 P)/m = -omega^2 P $

  #boxed[$ cases(
    dot(Q) &= m omega^2 P,
    dot(P) &= -Q/m
  ) quad => quad cases(
    dot.double(Q) &= -omega^2 Q,
    dot.double(P) &= -omega^2 P
  ) $]

  Both $Q$ and $P$ satisfy the harmonic oscillator equation. The transformation exchanges the roles of coordinate and momentum, revealing the symmetry $H(q, p) = K(P, Q)$ (up to constants).
]

#pagebreak()

#pbm("9.10")[
  Solve for $q(t)$ and $p(t)$ via $Q(t)$ and $P(t)$ using the canonical transformation:
  $ cases(
    display(q(Q, P, t) = sqrt(2P/(m omega)) sin Q),
    display(p(Q, P, t) = sqrt(2 m omega P) cos Q)
  ) $

  with Kamiltonian $K(Q, P, t) = omega P$.
]

#solution[
  *Verify canonicality via Poisson brackets:*

  The transformation is canonical if:
  $ {q, p}_(Q,P) = 1, quad {q, q}_(Q,P) = 0, quad {p, p}_(Q,P) = 0 $

  Compute partial derivatives:
  $ cases(
    pdv(q, Q) &= sqrt(2P/(m omega)) cos Q,
    pdv(q, P) &= 1/(sqrt(2 m omega P)) sin Q,
    pdv(p, Q) &= -sqrt(2 m omega P) sin Q,
    pdv(p, P) &= sqrt(m omega/(2P)) cos Q
  ) $

  Check ${q, p}_(Q,P)$:
  $ {q, p}_(Q,P) &= pdv(q, Q) pdv(p, P) - pdv(q, P) pdv(p, Q) \
  & = sqrt(2P/(m omega)) cos Q dot sqrt(m omega/(2P)) cos Q - 1/(sqrt(2 m omega P)) sin Q dot (-sqrt(2 m omega P) sin Q) \
  &= cos^2 Q + sin^2 Q = 1 quad checkmark $

  ${q, q}_(Q,P) = 0$ and ${p, p}_(Q,P) = 0$ trivially. The transformation is canonical.

  *Solve Kamiltonian equations:*

  $ K(Q, P, t) = omega P $

  $ cases(
    dot(Q) &= pdv(K, P) = omega,
    dot(P) &= -pdv(K, Q) = 0
  ) $

  Integrating:
  #boxed[$ cases(
    Q(t) &= omega t + Q(0),
    P(t) &= P(0)
  ) $]

  *Transform back to $(q, p)$:*

  $ cases(
    q(t) &= sqrt(2P(0)/(m omega) sin[omega t + Q(0)]),
    p(t) &= sqrt(2 m omega P(0) cos[omega t + Q(0)])
  ) $

  #boxed[$ cases(
    display(q(t) = sqrt(2P(0)/(m omega)) sin[omega t + Q(0)]),
    display(p(t) = sqrt(2 m omega P(0)) cos[omega t + Q(0)])
  ) $]

  *Determine constants from initial conditions:*

  At $t = 0$:
  $ cases(
    display(q(0) = sqrt(2P(0)/(m omega)) sin Q(0)),
    display(p(0) = sqrt(2 m omega P(0)) cos Q(0))
  ) $

  Squaring and adding:
  $ q(0)^2 + p(0)^2/(m^2 omega^2) = (2P(0))/(m omega) [sin^2 Q(0) + cos^2 Q(0)] = (2P(0))/(m omega) $

  $ P(0) = (m omega)/2 [q(0)^2 + p(0)^2/(m^2 omega^2)] = (m omega q(0)^2)/2 + p(0)^2/(2 m omega) $

  Dividing the equations:
  $ tan Q(0) = (m omega q(0))/(p(0)) quad => quad Q(0) = arctan((m omega q(0))/(p(0))) $

  *Compact form:*

  Define amplitude $A = sqrt(2P(0)/(m omega))$ and phase $phi = Q(0)$:

  #boxed[$ cases(
    q(t) &= A sin(omega t + phi),
    p(t) &= m omega A cos(omega t + phi)
  ) $]

  where:
  #boxed[$ cases(
    display(A = sqrt(q(0)^2 + p(0)^2/(m^2 omega^2))),
    display(phi = arctan((m omega q(0))/(p(0))))
  ) $]

  The canonical transformation converts the problem to one with cyclic coordinate $Q$, where $P = E/omega$ is conserved (proportional to energy). The coordinate $Q$ evolves uniformly in time, giving the familiar sinusoidal solution.
]
